map: 'Town05'

egoCar_spawn_point: [-15.73557, 200.606361, 0.275307]

control:
  base_speed: 0.4
  stuck_threshold: 0.1  # 停滞判定时间(s)
  stuck_speed_threshold: 2.5  # 停滞判定时间(s)

camera:
  resolution: [1152, 600]
  fov: 90
  positions:
    front: [2.0, 0.0, 1.3]
    rear: [-2.0, 0.0, 1.3]
    left: [0.0, 2.0, 1.3]
    right: [0.0, -2.0, 1.3]